name: Release to Chocolatey
on:
  workflow_dispatch:
    inputs:
      no-check-choco-version:
        required: false
        description: Disable version check in the Chocolatey community feed
        default: "false"
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: single-run
  cancel-in-progress: true

jobs:
  check:
    runs-on: windows-latest
    outputs:
      publish: ${{ steps.new-version-check.outputs.publish }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Find the latest version on Chocolatey
        run: choco search go-ipfs --exact | grep go-ipfs | awk '{ print $2 }' | tee choco-version
      - name: Find the latest version on dist.ipfs.io
        run: curl -s https://dist.ipfs.io/go-ipfs/versions | egrep "^v[0-9]+\.[0-9]+\.[0-9]+$" | tail -1 | cut -c 2- | tee dist-version
      - name: Check if the latest version is already published
        id: new-version-check
        run: |
          diff choco-version dist-version || true
          if cmp -s choco-version dist-version; then
            echo "::set-output name=publish::false"
            exit
          fi
          echo "::set-output name=publish::true"
  publish:
    runs-on: windows-latest
    needs: check
    if: needs.check.outputs.publish == 'true'
    environment: chocolatey
    defaults:
      run:
        shell: pwsh
        working-directory: ./go-ipfs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: choco install au
      - name: Build the latest release 🏗️
        env:
          NoCheckChocoVersion: ${{ github.event.inputs.no-check-choco-version || 'false' }}
        run: |
          ./update.ps1
          choco pack
      # if ./update.ps1 fails for any reason a bogus package
      # go-ipfs.0.0.0.nupkg is created.
      # we skip publishing when that happens.
      - name: Check if ok to proceed with publishing
        id: check
        run: |
          if test -e go-ipfs.0.0.0.nupkg; then
            echo "::set-output name=ok::false"
            exit
          fi
          echo "::set-output name=ok::true"
        shell: bash
      - name: Publish to Chocolatey 🍫
        if: ${{ steps.check.outputs.ok == 'true' }}
        run: choco push --key ${{ secrets.chocolatey_key }} --source "https://push.chocolatey.org"
